name: gradle_wrapper
description: A cli for download gradle-wrapper with proxy.
version: 0.3.0
repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.0

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  crypto: ^3.0.3
  dio: ^5.4.0
  path: ^1.9.0
  props: ^2.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

executables:
  gradle_wrapper:
